[2022-05-13 20:32:13,819] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:32:13,820] logger_util.py->print_log line:14 [INFO] 接口名称：成功获取token鉴权码
[2022-05-13 20:32:13,820] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:32:13,821] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:32:13,821] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:32:13,821] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 'wx8a9de038e93f77ab', 'secret': '8326fc915928dee3165720c910effb86'}
[2022-05-13 20:32:14,133] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 'access_token'}]
[2022-05-13 20:32:14,133] logger_util.py->print_log line:14 [INFO] 实际结果：{'access_token': '56_L45PDrwrulC76wq3tdXtalWVCddZvVEE9sqApmos8OxkWaSayfxG7Z9ljl-11nLBNu3VWwL2uh2jigmssZsJLGpj7kvuEk3ULzmqNCwZxuLe0ww3bG55DB0XwOKDvIRp1WtAI-ZchRQ7d3AZRVQaACAHLG', 'expires_in': 7200}
[2022-05-13 20:32:14,133] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:32:14,133] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:32:14,136] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:32:14,136] logger_util.py->print_log line:14 [INFO] 接口名称：检查appid为空
[2022-05-13 20:32:14,136] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:32:14,137] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:32:14,137] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:32:14,137] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 100, 'secret': '8326fc915928dee3165720c910effb86'}
[2022-05-13 20:32:14,181] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 40013}]
[2022-05-13 20:32:14,181] logger_util.py->print_log line:14 [INFO] 实际结果：{'errcode': 40013, 'errmsg': 'invalid appid rid: 627e4fce-040766f6-4b2bfb61'}
[2022-05-13 20:32:14,181] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:32:14,181] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:32:14,184] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:32:14,184] logger_util.py->print_log line:14 [INFO] 接口名称：检查secret为空1
[2022-05-13 20:32:14,184] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:32:14,185] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:32:14,185] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:32:14,185] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 'wx8a9de038e93f77ab', 'secret': ''}
[2022-05-13 20:32:14,298] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 41004}]
[2022-05-13 20:32:14,298] logger_util.py->print_log line:14 [INFO] 实际结果：{'errcode': 41004, 'errmsg': 'appsecret missing rid: 627e4fce-4e7af95b-1b8a8a95'}
[2022-05-13 20:32:14,298] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:32:14,299] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:32:14,301] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:32:14,302] logger_util.py->print_log line:14 [INFO] 接口名称：MD5加密接口
[2022-05-13 20:32:14,302] logger_util.py->print_log line:14 [INFO] 请求方式：post
[2022-05-13 20:32:14,302] logger_util.py->print_log line:14 [INFO] 请求路径：http://101.34.221.219:5000/md5login
[2022-05-13 20:32:14,302] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:32:14,302] logger_util.py->print_log line:14 [INFO] 请求data参数：{'username': '21232f297a57a5a743894a0e4a801fc3', 'password': '202cb962ac59075b964b07152d234b70'}
[2022-05-13 20:32:14,364] logger_util.py->print_log line:14 [INFO] 预期结果：[{'contains': 'MD5加密登陆成功'}]
[2022-05-13 20:32:14,364] logger_util.py->print_log line:14 [INFO] 实际结果：{'error_code': 0, 'message': 'MD5加密登陆成功！'}
[2022-05-13 20:32:14,364] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:32:14,364] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:32:14,370] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:32:14,370] logger_util.py->print_log line:14 [INFO] 接口名称：MD5加密接口
[2022-05-13 20:32:14,370] logger_util.py->print_log line:14 [INFO] 请求方式：post
[2022-05-13 20:32:14,370] logger_util.py->print_log line:14 [INFO] 请求路径：http://101.34.221.219:5000/base64login
[2022-05-13 20:32:14,370] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:32:14,370] logger_util.py->print_log line:14 [INFO] 请求data参数：{'username': 'None', 'password': 'None'}
[2022-05-13 20:32:14,425] logger_util.py->print_log line:14 [INFO] 预期结果：[{'contains': 'Base64加密登陆成功'}]
[2022-05-13 20:32:14,425] logger_util.py->print_log line:14 [INFO] 实际结果：{'error_code': 101, 'message': 'Base64加密登陆失败'}
[2022-05-13 20:32:14,425] logger_util.py->error_log line:10 [ERROR] contains断言失败：返回结果中没有Base64加密登陆成功
[2022-05-13 20:32:14,426] logger_util.py->error_log line:10 [ERROR] 断言报错：Traceback (most recent call last):
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 22, in assert_result
    flag = contains_assert(value, sj_result)
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 75, in contains_assert
    error_log("contains断言失败：返回结果中没有"+str(value)+"")
  File "D:\workspace\pythonwork\vip_pytest_one\commons\logger_util.py", line 11, in error_log
    raise AssertionError(message)
AssertionError: contains断言失败：返回结果中没有Base64加密登陆成功

[2022-05-13 20:32:14,426] logger_util.py->error_log line:10 [ERROR] 规范YAML测试用例报错：断言报错：Traceback (most recent call last):
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 22, in assert_result
    flag = contains_assert(value, sj_result)
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 75, in contains_assert
    error_log("contains断言失败：返回结果中没有"+str(value)+"")
  File "D:\workspace\pythonwork\vip_pytest_one\commons\logger_util.py", line 11, in error_log
    raise AssertionError(message)
AssertionError: contains断言失败：返回结果中没有Base64加密登陆成功

