[2022-05-13 20:20:00,988] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:20:00,989] logger_util.py->print_log line:14 [INFO] 接口名称：成功获取token鉴权码
[2022-05-13 20:20:00,989] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:20:00,990] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:20:00,991] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:20:00,991] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 'wx8a9de038e93f77ab', 'secret': '8326fc915928dee3165720c910effb86'}
[2022-05-13 20:20:01,330] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 'access_token'}]
[2022-05-13 20:20:01,330] logger_util.py->print_log line:14 [INFO] 实际结果：{'access_token': '56_pMDSqgA-KK8xLZOsVG39_ueKvF3UgPwLyVGRhp-yDdpvb9ljxbsbo68-KjUbdzeX6o5jZFw4MEyAB4jIQU0fq6SzZJsfwOcB7Pr5Xz2Bif4B1Dz6Blgcij7G1AYP6PVlJDZkZnukmceWqJ8AEGGaAAALNN', 'expires_in': 7200}
[2022-05-13 20:20:01,330] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:20:01,330] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:20:01,333] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:20:01,333] logger_util.py->print_log line:14 [INFO] 接口名称：检查appid为空
[2022-05-13 20:20:01,333] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:20:01,334] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:20:01,334] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:20:01,334] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 100, 'secret': '8326fc915928dee3165720c910effb86'}
[2022-05-13 20:20:01,373] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 40013}]
[2022-05-13 20:20:01,373] logger_util.py->print_log line:14 [INFO] 实际结果：{'errcode': 40013, 'errmsg': 'invalid appid rid: 627e4cf1-1fa698d0-00240f74'}
[2022-05-13 20:20:01,373] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:20:01,374] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:20:01,378] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:20:01,378] logger_util.py->print_log line:14 [INFO] 接口名称：检查secret为空1
[2022-05-13 20:20:01,378] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:20:01,379] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:20:01,379] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:20:01,379] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 'wx8a9de038e93f77ab', 'secret': ''}
[2022-05-13 20:20:01,489] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 41004}]
[2022-05-13 20:20:01,489] logger_util.py->print_log line:14 [INFO] 实际结果：{'errcode': 41004, 'errmsg': 'appsecret missing rid: 627e4cf1-71283890-79da6c28'}
[2022-05-13 20:20:01,489] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:20:01,489] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:20:01,492] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:20:01,492] logger_util.py->print_log line:14 [INFO] 接口名称：MD5加密接口
[2022-05-13 20:20:01,492] logger_util.py->print_log line:14 [INFO] 请求方式：post
[2022-05-13 20:20:01,492] logger_util.py->print_log line:14 [INFO] 请求路径：http://101.34.221.219:5000/md5login
[2022-05-13 20:20:01,492] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:20:01,492] logger_util.py->print_log line:14 [INFO] 请求data参数：{'username': '21232f297a57a5a743894a0e4a801fc3', 'password': '202cb962ac59075b964b07152d234b70'}
[2022-05-13 20:20:01,544] logger_util.py->print_log line:14 [INFO] 预期结果：[{'contains': 'MD5加密登陆成功!'}]
[2022-05-13 20:20:01,544] logger_util.py->print_log line:14 [INFO] 实际结果：{'error_code': 0, 'message': 'MD5加密登陆成功！'}
[2022-05-13 20:20:01,544] logger_util.py->error_log line:10 [ERROR] contains断言失败：返回结果中没有MD5加密登陆成功!
[2022-05-13 20:20:01,545] logger_util.py->error_log line:10 [ERROR] 断言报错：Traceback (most recent call last):
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 22, in assert_result
    flag = contains_assert(value, sj_result)
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 75, in contains_assert
    error_log("contains断言失败：返回结果中没有"+str(value)+"")
  File "D:\workspace\pythonwork\vip_pytest_one\commons\logger_util.py", line 11, in error_log
    raise AssertionError(message)
AssertionError: contains断言失败：返回结果中没有MD5加密登陆成功!

[2022-05-13 20:20:01,545] logger_util.py->error_log line:10 [ERROR] 规范YAML测试用例报错：断言报错：Traceback (most recent call last):
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 22, in assert_result
    flag = contains_assert(value, sj_result)
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 75, in contains_assert
    error_log("contains断言失败：返回结果中没有"+str(value)+"")
  File "D:\workspace\pythonwork\vip_pytest_one\commons\logger_util.py", line 11, in error_log
    raise AssertionError(message)
AssertionError: contains断言失败：返回结果中没有MD5加密登陆成功!

