[2022-05-13 20:15:37,744] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:15:37,744] logger_util.py->print_log line:14 [INFO] 接口名称：成功获取token鉴权码
[2022-05-13 20:15:37,744] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:15:37,746] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:15:37,746] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:15:37,746] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 'wx8a9de038e93f77ab', 'secret': '8326fc915928dee3165720c910effb86'}
[2022-05-13 20:15:38,043] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 'access_token'}]
[2022-05-13 20:15:38,043] logger_util.py->print_log line:14 [INFO] 实际结果：{'access_token': '56_LCYdboAsLY3-NkrGxmB6olm5y9ZC9iU_Lf9W5HLIDzNjlLwh5vPF2sXFNKzzABpNhtlE_5An6MV7gFtkVS_jTRB0jxnAagxAB1-JXBoAn0C5beSs0sogMcIY9bTpCnI1pCVS37dnD2Pxi6L_CKEaAIAKSM', 'expires_in': 7200}
[2022-05-13 20:15:38,044] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:15:38,044] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:15:38,048] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:15:38,048] logger_util.py->print_log line:14 [INFO] 接口名称：检查appid为空
[2022-05-13 20:15:38,048] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:15:38,049] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:15:38,049] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:15:38,049] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 100, 'secret': '8326fc915928dee3165720c910effb86'}
[2022-05-13 20:15:38,093] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 40013}]
[2022-05-13 20:15:38,093] logger_util.py->print_log line:14 [INFO] 实际结果：{'errcode': 40013, 'errmsg': 'invalid appid rid: 627e4bea-1c5292fe-0612a220'}
[2022-05-13 20:15:38,094] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:15:38,094] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:15:38,097] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:15:38,097] logger_util.py->print_log line:14 [INFO] 接口名称：检查secret为空1
[2022-05-13 20:15:38,097] logger_util.py->print_log line:14 [INFO] 请求方式：get
[2022-05-13 20:15:38,098] logger_util.py->print_log line:14 [INFO] 请求路径：https://api.weixin.qq.com/cgi-bin/token
[2022-05-13 20:15:38,098] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:15:38,098] logger_util.py->print_log line:14 [INFO] 请求params参数：{'grant_type': 'client_credential', 'appid': 'wx8a9de038e93f77ab', 'secret': ''}
[2022-05-13 20:15:38,229] logger_util.py->print_log line:14 [INFO] 预期结果：[{'codes': {'status_code': 200}}, {'contains': 41004}]
[2022-05-13 20:15:38,230] logger_util.py->print_log line:14 [INFO] 实际结果：{'errcode': 41004, 'errmsg': 'appsecret missing rid: 627e4bea-7a5dc57d-7459f772'}
[2022-05-13 20:15:38,230] logger_util.py->print_log line:14 [INFO] 接口测试成功
[2022-05-13 20:15:38,230] logger_util.py->print_log line:14 [INFO] ----------接口测试结束----------

[2022-05-13 20:15:38,234] logger_util.py->print_log line:14 [INFO] ----------接口测试开始----------
[2022-05-13 20:15:38,234] logger_util.py->print_log line:14 [INFO] 接口名称：MD5加密接口
[2022-05-13 20:15:38,234] logger_util.py->print_log line:14 [INFO] 请求方式：post
[2022-05-13 20:15:38,234] logger_util.py->print_log line:14 [INFO] 请求路径：http://101.34.221.219:5000/md5login
[2022-05-13 20:15:38,234] logger_util.py->print_log line:14 [INFO] 请求headers参数：None
[2022-05-13 20:15:38,235] logger_util.py->print_log line:14 [INFO] 请求data参数：{'username': 'None', 'password': 'None'}
[2022-05-13 20:15:38,283] logger_util.py->print_log line:14 [INFO] 预期结果：[{'contains': 'MD5加密登陆成功!'}]
[2022-05-13 20:15:38,284] logger_util.py->print_log line:14 [INFO] 实际结果：{'error_code': 101, 'message': 'MD5加密登陆失败'}
[2022-05-13 20:15:38,284] logger_util.py->error_log line:10 [ERROR] contains断言失败：返回结果中没有MD5加密登陆成功!
[2022-05-13 20:15:38,292] logger_util.py->error_log line:10 [ERROR] 断言报错：Traceback (most recent call last):
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 22, in assert_result
    flag = contains_assert(value, sj_result)
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 75, in contains_assert
    error_log("contains断言失败：返回结果中没有"+str(value)+"")
  File "D:\workspace\pythonwork\vip_pytest_one\commons\logger_util.py", line 11, in error_log
    raise AssertionError(message)
AssertionError: contains断言失败：返回结果中没有MD5加密登陆成功!

[2022-05-13 20:15:38,293] logger_util.py->error_log line:10 [ERROR] 规范YAML测试用例报错：断言报错：Traceback (most recent call last):
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 22, in assert_result
    flag = contains_assert(value, sj_result)
  File "D:\workspace\pythonwork\vip_pytest_one\commons\assert_utils.py", line 75, in contains_assert
    error_log("contains断言失败：返回结果中没有"+str(value)+"")
  File "D:\workspace\pythonwork\vip_pytest_one\commons\logger_util.py", line 11, in error_log
    raise AssertionError(message)
AssertionError: contains断言失败：返回结果中没有MD5加密登陆成功!

